version: 2

jobs:
  build:
    docker:
      - image: ruby:2.5
      - image: amazon/dynamodb-local
        environment:
          MAX_HEAP_SIZE: 1024m
          HEAP_NEWSIZE: 512m

    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "Gemfile.lock" }}-{{ checksum "Appraisals" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            BUNDLE_PATH=$(pwd)/vendor/bundle bundle exec appraisal install
      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}-{{ checksum "Appraisals" }}
      - run: bundle exec appraisal rspec --format progress



